site_name: Moov Documentation
pages:
- Overview: index.md
- About: about.md
- ACH:
  - Overview: ach/index.md
  - 'ACH File Structure': ach/file-structure.md
- X9:
  - Overview: x9/index.md
  - 'X9 File Structure': x9/file-structure.md
- Tutorials:
    - 'Running ACH Server': tutorials/ach-server.md
    - 'Local Dev with Moov': tutorials/local-dev.md
theme: readthedocs
extra_css:
  - extra.css
repo_url: https://github.com/moov-io/docs/
google_analytics: ['UA-118148273-1', 'moov.io']
